### ISSUE TITLE
Error on saving records with file references

### ISSUE THREAD

**Issue by dahaupt** [b13/unlocalizedcrop#4]
```
PHP Warning: Undefined array key "l10n_parent" in 
/var/www/html/public/typo3conf/ext/unlocalizedcrop/Classes/Hooks/DataHandlerCropModifier.php line 61
```

**Versions:**
TYPO3: 11.5.24
PHP: 8.1
Extension: dev-master

**Comment by bmack** [comment]
didn't know this extension was compatible with v11 yet...

**Comment by dahaupt** [comment]
@bmack The tag `2.1.0` actually declared support for v11, but it was not added to current `master`. 

Please excuse me, if I am acting too fast here. I'll provide a PR shortly. I can also help to fix any additional issues with TYPO3 v11.
